/**
 * Códigos de erro estáveis do contrato v3 (spec §17.1).
 *
 * O código, não a mensagem, é o contrato: consumidores fazem branch sobre ele.
 * Renomear ou remover uma entrada aqui é breaking change.
 */
export const RestQueryErrorCode = {
  QUERY_SYNTAX_INVALID: 'QUERY_SYNTAX_INVALID',
  QUERY_SYNTAX_UNKNOWN_PARAM: 'QUERY_SYNTAX_UNKNOWN_PARAM',
  FIELD_NOT_ALLOWED: 'FIELD_NOT_ALLOWED',
  FIELD_NOT_FOUND: 'FIELD_NOT_FOUND',
  RELATION_NOT_FOUND: 'RELATION_NOT_FOUND',
  OPERATOR_NOT_ALLOWED: 'OPERATOR_NOT_ALLOWED',
  OPERATOR_TYPE_MISMATCH: 'OPERATOR_TYPE_MISMATCH',
  FILTER_VALUE_INVALID: 'FILTER_VALUE_INVALID',
  PAGINATION_INVALID: 'PAGINATION_INVALID',
  SORT_CONFLICT: 'SORT_CONFLICT',
  CAPABILITY_UNAVAILABLE: 'CAPABILITY_UNAVAILABLE',
  PORTABILITY_PROFILE_MISMATCH: 'PORTABILITY_PROFILE_MISMATCH',
  SOURCE_CONFIGURATION_INVALID: 'SOURCE_CONFIGURATION_INVALID',
  ADAPTER_CONTRACT_VIOLATION: 'ADAPTER_CONTRACT_VIOLATION',
} as const;

export type RestQueryErrorCode =
  (typeof RestQueryErrorCode)[keyof typeof RestQueryErrorCode];
