services:
  postgres:
    image: postgres:15-alpine
    container_name: multi-access-postgres-sample
    environment:
      POSTGRES_DB: multi_acessos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: multi-access-postgres-data
